data:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: true
    num_workers: 4

model:
    type: "sa"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 32
    n_epochs: 1500
    n_iters: 500000
    snapshot_freq: 25
    validation_freq: 2000

sampling:
    batch_size: 500
    last_only: True

# optim:
#     weight_decay: 0.03
#     optimizer: "AdamW"
#     lr: 0.0002
#     beta1: 0.99
#     beta2: 0.999
#     grad_clip: 1.0
optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    beta2: 0.999
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
